name: nanoapi_build_and_deploy

on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
        - name: Build and deploy via Nano API
          uses: Nano-API/Deploy@version/0
          with:
            apiKey: ${{ secrets.NANO_API_TOKEN }}
            buildConfigId: '668174e3ac627b492a82f7c6'
            commitSHA: ${{ github.sha }}
